added vrv
matthewdias/media-strategies pull request #7
Opened 2017-07-02 00:03 UTC by tejassharma96

2017-07-02 23:34 UTC, matthewdias requested changes
Thanks! Just some ocd stuff. Sorry for being anal about this 😅

2017-07-02 23:34 UTC, matthewdias commented on strategies/vrv.js
> +  return document.querySelector(".series").innerText
can you use single quotes throughout this file?

2017-07-02 23:34 UTC, matthewdias commented on strategies/vrv.js
> +  return !(document.querySelector("#player > video").paused)
Is there ever a chance of there being two video elements rendered at the same time? If not we can get rid of the `#player > `.

2017-07-02 23:34 UTC, matthewdias commented on strategies/vrv.js
> +)    video.play()
move this closing paren to the previous line

2017-07-03 21:03 UTC, tejassharma96 commented
ok, so after further testing, VRV appears to just not want to give me the video player info sometimes... Like sometimes I can access it with just document.querySelector('video'), and sometimes it just consistently gives me nothing. I'm gonna remove the video control stuff completely tbh and add a * to the readme for VRV

2017-07-04 21:52 UTC, matthewdias approved these changes

2017-07-04 22:04 UTC, merged